### PR TITLE
Extract comments

### LINKED ISSUE #22: Can we add a feature to take the text of the comments of each post?

### PR DESCRIPTION
**Pull request by neon-ninja**
This PR adds an option to extract comments from posts. Sample usage is as follows:

`posts = list(get_posts(post_urls=["https://m.facebook.com/story.php?story_fbid=1917763655047425&id=285708024919671"], cookies="cookies.txt", options={"comments":True}))`

Note that comments are only extracted if the option is set, so no comments are extracted by default.
If no cookies are provided, facebook does not provide links to commenter profiles, so commenter_url will be set to None
This should fix #22 

Results:

```
[{'available': True,
  'comments': 0,
  'comments_full': [{'comment_id': '1918578434965947',
                     'comment_text': 'Can you buy them anywhere?????',
                     'comment_time': datetime.datetime(2021, 3, 19, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Jess Bee Adlington',
                     'commenter_url': 'https://facebook.com/jess.anshaw?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918657281624729',
                     'comment_text': 'Jason Salt',
                     'comment_time': datetime.datetime(2021, 3, 20, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Christine Salt',
                     'commenter_url': 'https://facebook.com/christine.salt.14?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918024338354690',
                     'comment_text': 'Joshua Foti',
                     'comment_time': datetime.datetime(2021, 3, 19, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Paris Atkins',
                     'commenter_url': 'https://facebook.com/paris.atkins15?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918010668356057',
                     'comment_text': 'Jarrod Styles',
                     'comment_time': datetime.datetime(2021, 3, 19, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Hannah Styles',
                     'commenter_url': 'https://facebook.com/hannah.styles.96?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1917836111706846',
                     'comment_text': 'Caitlin Henderson',
                     'comment_time': datetime.datetime(2021, 3, 18, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Alex White',
                     'commenter_url': 'https://facebook.com/alexwhitedgm?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1919380094885781',
                     'comment_text': 'Kyall Rotumah Corey Preacher',
                     'comment_time': datetime.datetime(2021, 3, 20, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Rebekah Nicholson',
                     'commenter_url': 'https://facebook.com/rebekah.nicholson.3?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918548978302226',
                     'comment_text': 'Gary Irving',
                     'comment_time': datetime.datetime(2021, 3, 19, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Jessica Holt',
                     'commenter_url': 'https://facebook.com/jessica.holt.393?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918658154957975',
                     'comment_text': 'Liam Walker :o do u think these are cute',
                     'comment_time': datetime.datetime(2021, 3, 20, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Chelsie Foster',
                     'commenter_url': 'https://facebook.com/chelsie.foster.5?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1919431868213937',
                     'comment_text': 'Cody Carter',
                     'comment_time': datetime.datetime(2021, 3, 21, 0, 0),
                     'commenter_meta': None,
                     'commenter_name': 'Alex Austin',
                     'commenter_url': 'https://facebook.com/Nephtis?fref=nf&rc=p&refid=52&__tn__=R'},
                    {'comment_id': '1918650554958735',
                     'comment_text': 'I just want that Mario Sunshine Pin with '
                                     'FLUDD. Please? :p',
                     'comment_time': datetime.datetime(2021, 3, 20, 0, 0),
                     'commenter_meta': 'Top fan',
                     'commenter_name': 'Steve Gigacz',
                     'commenter_url': 'https://facebook.com/steven.gigacz?fref=nf&rc=p&refid=52&__tn__=R'}],
  'factcheck': None,
  'image': None,
  'images': [],
  'is_live': False,
  'likes': 0,
  'link': 'https://www.nintendo.com.au/supermario35/quiz/?fbclid=IwAR2mJMB5p1mdw4mPONuaOpMjR5_5fO2uQs3_H3-qVLklKtfEbBpkVNp7gkg',
  'post_id': '1917763655047425',
  'post_text': 'ICYMI – Enter the draw for one of two Super Mario Bros. 35th '
               'Anniversary pin sets!\n'
               '\n'
               'Simply sign into your Nintendo Account and complete our Mario '
               'Quiz – you’ll also score 50 My Nintendo Platinum Points when '
               'you finish!\n'
               '\n'
               '🖱 Click here: https://www.nintendo.com.au/supermario35/quiz/\n'
               '\n'
               '◾ This promotion is only available to residents of Australia '
               'and New Zealand.\n'
               '◾ Pin set includes pins displayed only. Figurines not included',
  'post_url': 'https://facebook.com/story.php?story_fbid=1917763655047425&id=285708024919671',
  'shared_post_id': None,
  'shared_post_url': None,
  'shared_text': '',
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shares': 0,
  'text': 'ICYMI – Enter the draw for one of two Super Mario Bros. 35th '
          'Anniversary pin sets!\n'
          '\n'
          'Simply sign into your Nintendo Account and complete our Mario Quiz '
          '– you’ll also score 50 My Nintendo Platinum Points when you '
          'finish!\n'
          '\n'
          '🖱 Click here: https://www.nintendo.com.au/supermario35/quiz/\n'
          '\n'
          '◾ This promotion is only available to residents of Australia and '
          'New Zealand.\n'
          '◾ Pin set includes pins displayed only. Figurines not included',
  'time': datetime.datetime(2021, 3, 19, 19, 0),
  'user_id': '285708024919671',
  'username': 'Nintendo',
  'video': None,
  'video_id': None,
  'video_thumbnail': None}]
```

### CODE REVIEW

**Comment by dhananghs** [comment]
hi @neon-ninja thanks fo your awesome work!
mind to explain how do I get the cookies to be put on cookies.txt?
cheers!

**Comment by neon-ninja** [comment]
> hi @neon-ninja thanks fo your awesome work!
> mind to explain how do I get the cookies to be put on cookies.txt?
> cheers!

See https://github.com/kevinzg/facebook-scraper/issues/28#issuecomment-793066983

**Comment by dhananghs** [comment]
> > hi @neon-ninja thanks fo your awesome work!
> > mind to explain how do I get the cookies to be put on cookies.txt?
> > cheers!
> 
> See [#28 (comment)](https://github.com/kevinzg/facebook-scraper/issues/28#issuecomment-793066983)

thank you!

**Comment by pepe3lsr** [comment]
@neon-ninja First of all, THANKS A LOT !!! For this huge work, its an great tool!! 
I have a problem with the example of this page
**posts = list(get_posts(post_urls=["https://m.facebook.com/story.php?story_fbid=1917763655047425&id=285708024919671"], cookies="cookies.txt", options={"comments":True}))**
It returns 

ValueError: You need to specify either account or group

By the way, do you have any example for comments extraction , I couldn't get the comments of any of the post I try.

**Comment by neon-ninja** [comment]
> @neon-ninja First of all, THANKS A LOT !!! For this huge work, its an great tool!!
> I have a problem with the example of this page
> **posts = list(get_posts(post_urls=["https://m.facebook.com/story.php?story_fbid=1917763655047425&id=285708024919671"], cookies="cookies.txt", options={"comments":True}))**
> It returns
> 
> ValueError: You need to specify either account or group
> 
> By the way, do you have any example for comments extraction , I couldn't get the comments of any of the post I try.

That's an old error message - you need to update

**Comment by aldrinken214** [comment]
Hello @neon-ninja ! Thanks for this tool btw! Just here to ask if it's recommendable to extract both posts and comments at the same time (code)? We've written two different set of programs: 1) extract just the posts and 2) its comments/replies to prevent banning. But I feel like we're gonna be making the same amount of requests anyway (at least with getting comments/replies, since we'll still be requesting post parameters in the process).

**Comment by neon-ninja** [comment]
For small extraction jobs, it's fine to couple to processes. For larger extraction jobs I recommend decoupling them

**Pull request merged**
