### PR TITLE
Days limit

### PR DESCRIPTION
**Pull request by davitjnz**
Adding days_limit command line argument to scrap the post for specified days

### CODE REVIEW

**Comment by kevinzg** [comment]
This is good, but it should somehow handle sticky posts.

**Comment by DatoJanez** [comment]
Thanks @kevinzg, 

We came to the same problem and I came out with a quick (and dirty) solution by adding _first_possible_pinned_post_passed_  variable to skip first post. It kind of works at this moment.

**Comment by grubeli** [comment]
Would be useful

**Comment by neon-ninja** [comment]
Thanks for your pull request! This feature request came up again with a few other things in https://github.com/kevinzg/facebook-scraper/issues/498, so I've implemented it https://github.com/kevinzg/facebook-scraper/commit/1c9558a78405d940462e6de3ec27feaffff802cd and https://github.com/kevinzg/facebook-scraper/commit/9e5592f1b812407fbbe04ca7a19a387501fbe720.

**Pull request closed without merging**
