### PR TITLE
Video thumbnails

### PR DESCRIPTION
**Pull request by krzygorz**
An extractor for video thumbnails. Adds a new field, `video_thumbnail`.

### CODE REVIEW

**Comment by kevinzg** [comment]
I tried with a couple of pages but every post with a video had the video thumbnail field as `None`. Is it still working?

**Comment by krzygorz** [comment]
Hmm... It still Works On My Machine™, could you post some examples? Here's the code I tested it with:

```python
import facebook_scraper

for page in ['bbcnews', 'nintendo']:
    for post in facebook_scraper.get_posts(page, pages=8):
        print("-------------", post['post_url'], "---------------")
        if post['image']:
            print("IMAGE")#, post['image'])
        if post['video']:
            print("VIDEO", post['video_thumbnail'])
```

**Comment by kevinzg** [comment]
```python
import facebook_scraper
for post in facebook_scraper.get_posts('bbcnews'):
    if post['video']:
        print(post['video_thumbnail'])
```
It just prints a lot of `None`s.

The selector `i[data-sigil="playInlineVideo"]` doesn't select anything. Removing the first `i` from it selects an element, but that element doesn't have a `style` attribute, it does have a `src` attribute with an image that looks like a thumbnail, so maybe we are getting different HTML.

**Comment by krzygorz** [comment]
Interesting, maybe this is some sort of a/b test. I'll experiment with proxies and try to come up with a more reliable extractor.

**Comment by krzygorz** [comment]
I've had no luck reproducing this issue. I tried many different proxies, but I never got a `None`. Perhaps more importantly, I used the test cassettes, which I assumed would contain the same kind of responses you're getting now, yet somehow the extractor still returns an (expired) url.

Also, I had a minor git screw-up and force pushed my branch, hope this doesn't cause trouble.

**Comment by kevinzg** [comment]
I just tried again and this time it worked. Weird. I'm gonna merge it.

**Pull request merged**
