### PR TITLE
added minimized page info function

### PR DESCRIPTION
**Pull request by jlp-io**

### CODE REVIEW

**Review by neon-ninja — COMMENTED** [review]
This seems like needless copy pasting of code from get_page_info. Why not simply have get_page_info take an argument stating whether extra requests are allowed?

**Comment by jlp-io** [comment]
hi mate, I changed the code as requested. 

let me know if it's acceptable for merging. it's a quick fix but it might help with speed

**Comment by neon-ninja** [comment]
Thanks. It would be better if you used the kwargs dictionary, aa changing the signature would break the invocation from __init__.py. Also, the option should default to true, to not break existing code relying on this functionality.

**Comment by neon-ninja** [comment]
Thanks for your contribution!

**Comment by jlp-io** [comment]
How do I set a kwargs value to False when making a function call to get_page_info ?

**Comment by jlp-io** [comment]
thanks. from the looks of it, the function runs very quick now when retrieving basic details!

**Pull request merged**
